env:
  global:
    - IMAGE_NAME=pybot
    - DEPLOY_BRANCHES="master staging"
    - AWS_REGION=us-east-2
    - secure: DcEpdVJ6LoHSLigVem++aZGn0kq74oyPIk/Zifz61NE7nDbustbXahgtMCkiv7dqyd1nqc6E/9S/DZ5dUoWPeeG/VPKkm+Ylk0jZcVLPwSd9S3oICLIZVwL8bG+FwYEY08kGl20rbTMAZT3zIhT0HMmw59UVYr7Lke9vLy2sZKi3nZv7L6miiIBwK3DFuUx3cPTtNXiaszBbUmFLNTNg6ehig2W+FwhHEG2wmd+On5nmArdaXfBDKMXT748aA2y3OG3PTrXdC5OEi0oIaf/8MimIJWzxkoMS8jFoyDSXFOCOzQucv7uAsZHZRACP2HHV5iqOLIo5E6dlONKJFP7TCYqYTzZF8Dz9TUjIMkr+zAeCMrlMzOCVD3qquUoW++s6F71IHGlavqZvMTApyaRCIZanwHk/Tb96/s87bsFPYoGrsInQjfhhPUHTCxZrkBqZg8UegbZJ+HyH+I0bK9WM5mFyeQ7swRFkaQ6MICmqWF0w8JrJUAkOci3Q6NO1+7NBDNT5F3arhHgKMHpw0ry3iuUU1I7Unh8QdzNIgdcAh7TAgI8n0CjBXHf22+ZI0ph4Og7blZ17h9idSj72Ll8a7Rnj3/FgtB7HE1nQMzZfBtiN6txZAhM1ADIDj6NmaIXF+2hkQDnGczGaLqNHlKb14nNfdiWnO8Wf9DKCFZS8iKk=
    - secure: XPvMPMkCIBORXmFSwnSVm6rOF1mHcipzgo9IdbFu87dFFC2mJG/T8UTbEyTLpjpM8WvcSawmpWHtqlhbHXnEj+6ugEongvYsl0wYh/KNU9oS5vw38CvxpvIIg3PyTS39Dp8QtP/y/EaeZPPQiN/soiNGQ0EQ9V/eazjO9Gc9vTvYfPdSc3Q4UjxAqf550L+pkEF6NSh0Lo3ShCr1sai+XCvyvYeTTtwZzufIzq/aNxs+dPUc0FDXdZ5L+J2Ds/yxXAaVcQzSfhdxV1igCcQ6HesndsrrM6DIOTPtzFhpeA3RHaNxrAeh9ZXvYoLkXbyxEmraSRTx0PBjBLNkZNNorOB/ebWj3s1CK5I/3qrZ7WVIq/keDea1Ict9g7moYe8/OLQO0b0/gNqkR/jpepSbfxnEF41DNhJ2xSSE9niuEaUnpDpCibhLCqtXGbRK90dIjnkLHemxL8mrujwm7XDHcTK+GsA5ceBMHk0aQ9WDrKPCQGw8DlQ6EfgnOd/61Dq5vMZW8cC60h8EQNQFQ3KBgEEELpNSltvaf4FYA3Og+Vie/VStjCzDuGohghKiiaGFBWUGtaQGyr4cuwCI88iAU4/LiTz83JAv7+6tD+vsczV8Bdlg360Mquc01E7Vw9Qmtvh1kRWLicA6dUemrUqHO79izqAhhmLhz5dCBZOOGoM=
    - AIRTABLE_API_KEY=apiKey
    - AIRTABLE_BASE_KEY=baseKey
    - AIRTABLE_VERIFY=verify
    - ECS_CLUSTER_MASTER=python-oc-services
    - ECS_SERVICE_MASTER=pybot-svc
    - ECS_CLUSTER_STAGING=python-oc-services
    - ECS_SERVICE_STAGING=pybot-svc-staging
    - PIPENV_CACHE_DIR=~./.cache/pip
    - REMOTE_IMAGE_URL=docker.io/operationcode/pybot
    - DOCKER_REPO=operationcode/pybot
    - secure: gkdQPxnUpj14ggSfWsEqlpNVIfLlHvZN/g/m4WnPrlpQeMIjTMBjO+wYkjzm0SnBFFAAK8pJUbXjL9VNWL5avYdKpC9ZrW7jSvIaC8H24ooJfLLhpq+BxvW84yRx9YnI+xaJejkVz8PiicVbR7e2Qrvzb48e+phBAHXEHrzzaJuF7N7unCMN6dRKhofm8zPnEf0BQPQHFZrB5dbEQiYTuzDAtH7lHuS7x9CHhxo25Yd6hdxLn02gJN9cUQUJ9ZW3/7PjTdc7sxK3ulX8w2X2p+qifzHVgb3T1IaGAbY2XDGE/AIJfOrsKL2y61gfQ12j5XRd6e/Nq2+Ctk6KDtzMjOPzIfpAMSPKsHhuIc1pChy/3TKpV5fSgqlkl17biy1mtOvUH8HJ+1pBwmBKfMv8eKzSaSzMU93V0bvP85F+AhYmK1gD0WA+KEDxPN1ycFd7iekkL6BbM5J/M7ISvHbNQHI1sUj9tqiARZFYvxmzi2joMXpOTtt2tj7/SmuGegeXK6zLm4tDKlgYnu+7/IfaaUV0iWN/6+Hf2iM/Q0pFvk6gzQxeffidTPuw/1iroGXPq4yUcpSLkDzzT939C/8OaTW4raKD2uDiYiZ+mQvEDuyazj97rjtvQt8MH1GsrmD+weLWkUDSHmmIQJtjSPH2soiquEbBBAiW6BOt1s4gK7c=
    - secure: mZJ89mT8l/x/IYvhQrBIF1jxoxHzv2zsPGso96mU8wuJidHu5ixZA+Jo9z5xN+hFlGWh0WCP4uGUurpX2yvv1x6hb6wes7lM1uN4uSy5dpiU0pUnIWdkTGZTM90HgabhjEvM0hponQhAiK75zGCi8xKWenrGi0VmamzkO+p+QS0/1aGvOjQuyBkou9Bl6+8ywSC3+PrIBs9CRD0kAifg4ePKOWa17/nnCotPMaGjbEoATHuY/YE967ShqS/UhHoXXejgKBpOAB/l2x4MA3+oTKnuVYNWLGm4QhqhHodbgrkffCNpYnjrgU899RA300gv4Ybxa6Z232SBUfSf4meZjwMeYIrikkLCWT+5mmHUF+ICr9dpgeraO6zebTSfB8HoHsD1HJuPqA9mIn7BUHRGvGYLrPcUFy54qAQD0Yq7tpy5Ew2MX7Su0i1Kkhv7lw2aFNiBK6MWq9cSmSbD0EDOBv+Dzb7C6Vg/m4UP+8sg8uHUoYxP8ugLOz8XEJ/JMunVonB9p1r19unSQFeMBDZFS5QXvZ3z6/6s1IrvOa/PQKtOJaw4MTDXu6IXWBC+UTw9hVEAaWWltEhb7BkODOeF2iENiH4n4V0hkILLRll5IoTd5/nv6GmMPs2l0jGC1GDV7D3gsv7HmbBFeLxKDgPvYogXd/I+LuFrqCOPkNm5jZ4=

os: linux
cache: pip
sudo: required
language: python
dist: xenial
python: 3.7
install:
  - pip install pipenv
  - pipenv install --system --deploy --dev
script:
  - pytest
services:
  - docker
after_success:
  - bash bin/run.sh
notifications:
  slack:
    rooms:
      secure: WXY1MpTRyv7B+t0HhLGjkIfiujU7q4+CB6oyxFFqO62cSv4LgV2efoYS9qZCcxbNQNRnzBjVLWD+d0afXhhsBOrjTMadjJdc+mzZyKiS8Hc21ZK8vH8o7ivmbxT63hMTbYdXY5mPdOpd13zszCibJowE5g9ce1MA/W5VLuQlAxdLb5/hnIaAY5Ik5A03tC3jFiELF5n0f/+U4TWR2XYWl13Zh72oqARKvTSLCQg83yCA1gG3eniOZTOsk0uK2ob3IBpmlb7MM/wg6JNN/zEFQ2J5dxNpsSTVvq44dKDAG7ebWXuc7Ba2bkzqQsTvuzRaYUeXJEpHs9AmygmPa5ndnVcXYYv9EiwTI+hb49sZNaE4gPpnJVlSrSMCffdAb/63VeKn1am3mREbtt5oo1OU/jt5wyRU17e16j3AxykoTaAb4jJXSICLsUgP7svTj1ByQuWnyGL7/y394tftckxMDCiLtaBcOTtxsGNA6BuKYXs76jbjy9A4KLMWn1FJ5k9x9liVsedYqMZ7T/LqTTnwtk0QukroRHqtkbU1WPoZF59W9WZmCUvLiQaptvlBZ7cLOJCBOLUR0mZm/iJkDslScTzGxNm9XYiWCebtAi5R8TtZQfCZ2TcR5BOsV1kIvC/XZntA9Pm5etsGxe5yC032eq32HJH6xItJRnW/7O8MWlM=
