env:
  global:
    - IMAGE_NAME=pybot
    - DEPLOY_BRANCHES="master staging"
    - AWS_REGION=us-east-2
    - secure: DcEpdVJ6LoHSLigVem++aZGn0kq74oyPIk/Zifz61NE7nDbustbXahgtMCkiv7dqyd1nqc6E/9S/DZ5dUoWPeeG/VPKkm+Ylk0jZcVLPwSd9S3oICLIZVwL8bG+FwYEY08kGl20rbTMAZT3zIhT0HMmw59UVYr7Lke9vLy2sZKi3nZv7L6miiIBwK3DFuUx3cPTtNXiaszBbUmFLNTNg6ehig2W+FwhHEG2wmd+On5nmArdaXfBDKMXT748aA2y3OG3PTrXdC5OEi0oIaf/8MimIJWzxkoMS8jFoyDSXFOCOzQucv7uAsZHZRACP2HHV5iqOLIo5E6dlONKJFP7TCYqYTzZF8Dz9TUjIMkr+zAeCMrlMzOCVD3qquUoW++s6F71IHGlavqZvMTApyaRCIZanwHk/Tb96/s87bsFPYoGrsInQjfhhPUHTCxZrkBqZg8UegbZJ+HyH+I0bK9WM5mFyeQ7swRFkaQ6MICmqWF0w8JrJUAkOci3Q6NO1+7NBDNT5F3arhHgKMHpw0ry3iuUU1I7Unh8QdzNIgdcAh7TAgI8n0CjBXHf22+ZI0ph4Og7blZ17h9idSj72Ll8a7Rnj3/FgtB7HE1nQMzZfBtiN6txZAhM1ADIDj6NmaIXF+2hkQDnGczGaLqNHlKb14nNfdiWnO8Wf9DKCFZS8iKk=
    - secure: XPvMPMkCIBORXmFSwnSVm6rOF1mHcipzgo9IdbFu87dFFC2mJG/T8UTbEyTLpjpM8WvcSawmpWHtqlhbHXnEj+6ugEongvYsl0wYh/KNU9oS5vw38CvxpvIIg3PyTS39Dp8QtP/y/EaeZPPQiN/soiNGQ0EQ9V/eazjO9Gc9vTvYfPdSc3Q4UjxAqf550L+pkEF6NSh0Lo3ShCr1sai+XCvyvYeTTtwZzufIzq/aNxs+dPUc0FDXdZ5L+J2Ds/yxXAaVcQzSfhdxV1igCcQ6HesndsrrM6DIOTPtzFhpeA3RHaNxrAeh9ZXvYoLkXbyxEmraSRTx0PBjBLNkZNNorOB/ebWj3s1CK5I/3qrZ7WVIq/keDea1Ict9g7moYe8/OLQO0b0/gNqkR/jpepSbfxnEF41DNhJ2xSSE9niuEaUnpDpCibhLCqtXGbRK90dIjnkLHemxL8mrujwm7XDHcTK+GsA5ceBMHk0aQ9WDrKPCQGw8DlQ6EfgnOd/61Dq5vMZW8cC60h8EQNQFQ3KBgEEELpNSltvaf4FYA3Og+Vie/VStjCzDuGohghKiiaGFBWUGtaQGyr4cuwCI88iAU4/LiTz83JAv7+6tD+vsczV8Bdlg360Mquc01E7Vw9Qmtvh1kRWLicA6dUemrUqHO79izqAhhmLhz5dCBZOOGoM=
    - AIRTABLE_API_KEY=apiKey
    - AIRTABLE_BASE_KEY=baseKey
    - AIRTABLE_VERIFY=verify
    - ECS_CLUSTER_MASTER=python-oc-services
    - ECS_SERVICE_MASTER=pybot-svc
    - ECS_CLUSTER_STAGING=python-oc-services
    - ECS_SERVICE_STAGING=pybot-svc-staging
    - PIPENV_CACHE_DIR=~./.cache/pip
    - REMOTE_IMAGE_URL=docker.io/operationcodetest/pybot
    - DOCKER_REPO="operationcodetest/pybot"
    - secure: rOEZjJrYS1CVGBGlRWUgfzL+prI9OMSOd7e2l/Ki2OIoknkKcOxJYxgbDUaA2BLVS3zvzd2yRrxAOW3K/w6j/yzxDLFvZ2S/4G3wMdhgMN+yQnEIXfRwBmUTVpdL2qI4+fJD1nWjvlqJ3N6G1q5Ld87+h/Ixe03MHBv63fwBoIhImtg7mZCG2m1zIMJlCiV+ipiU0brFg80+Oz9rxM0xiTdI1tnDBJ9ySdIvpI/nR7ZskDWi3pXfa57iFGku3OpIf+5nRuNPP0xlrAsvcnTVsk3h2OOddFNNHxAKeqiaczBn56exhDs6rC/HAxom1wUbJB2I/kWRooIz+adUkpgJw9w5Wvt/vGHggAmoqLkeMmDG3PH+IaIu8dqg7D5Lrn2kdW/ImpC+E7CUZYhLGbl82DAnGl7RIU8QEq6fp9bwDbc3nQ3F0OIop7nq6tHBAojvuUnV8EN7de1o8mL4mW+u19d6kzLyYbUptl9arb8/VHJakkRcpK0n+Mdr3CwQOJbtUReNMNwaM99vNuYV2TLDRnP6yoQy2pU6+SSQN6xA8xnIqbTVSe7wam3x8Lj+rxvdu+a/7J4VIdsGSGYxs/7YiKiHkpqRLDUVeLMAQriJzO2QHPTLZJrHeYQALwLkuwLoNX8nT0DHSNYlskiyrWxZhuYu5dBSEYAkQ8+0wW0teY4=
    - secure: Lbu9pE+5b7+7cw65rSkkPDLx+bvmFTHFAeALpwruuOBJNdHkIatymJnPg3pROlz3Bli/F5zCBOGnimyVKRxQq8qbBZn+ImJKc7lFTQ8GIJ9/jo2ANtsacoipxoBGKTh9cqCwIron2HvP4IwzSvLebrvdQUDUL93HMVcfNqMsR2yZloJLflAoP5Vo33qOsCVCHbjlUWkSbYP03Aq5GrPahHIRrqdWl8rNCeJWbluH3UTv9FuhGgf/0PBA67rNHbL//WCjxvaTyHxJGCqRTUl4uFUyl8nJAEha4c/PDWYRDsDYdVPfV+7v8rVa0RX8xll9nFn3cICeBsZR0fw1ujzqgFE1EXSkiYwNj225sjfR2uRtjxHwMsCmsPZVZiSQF0pC8jqHFI5428tSW3O6oaCU/e5m/HuLc0coC/CAhxDTE28E8eBMZoupF1apBMnHqplmcU4E0TLIPZY1iK7QFkvqdulw4fIc9om9wV1D/GTDOoWogjaoILqdtuskrCtReabvWs8OBsjTHe0gsiAoYVBQ/3N1YxjEyzzWvATXmfo5wbHTuKBnjaROAQ2jM2sawnRDHSDNMdyxSmyx6tjYkHQX0Lhw17/srtkjzb+01tHZ8ZvEeuI7AfZzkmSpaE3juyaY1YIMDZRQRINfaBdA0rq0yVz988MdRly88m/xXcg4s9U=
os: linux
cache: pip
sudo: required
language: python
dist: xenial
python: 3.7
install:
  - pip install pipenv
  - pipenv install --system --deploy --dev
script:
  - pytest
services:
  - docker
after_success:
  - bash bin/run.sh
notifications:
  slack:
    rooms:
      secure: WXY1MpTRyv7B+t0HhLGjkIfiujU7q4+CB6oyxFFqO62cSv4LgV2efoYS9qZCcxbNQNRnzBjVLWD+d0afXhhsBOrjTMadjJdc+mzZyKiS8Hc21ZK8vH8o7ivmbxT63hMTbYdXY5mPdOpd13zszCibJowE5g9ce1MA/W5VLuQlAxdLb5/hnIaAY5Ik5A03tC3jFiELF5n0f/+U4TWR2XYWl13Zh72oqARKvTSLCQg83yCA1gG3eniOZTOsk0uK2ob3IBpmlb7MM/wg6JNN/zEFQ2J5dxNpsSTVvq44dKDAG7ebWXuc7Ba2bkzqQsTvuzRaYUeXJEpHs9AmygmPa5ndnVcXYYv9EiwTI+hb49sZNaE4gPpnJVlSrSMCffdAb/63VeKn1am3mREbtt5oo1OU/jt5wyRU17e16j3AxykoTaAb4jJXSICLsUgP7svTj1ByQuWnyGL7/y394tftckxMDCiLtaBcOTtxsGNA6BuKYXs76jbjy9A4KLMWn1FJ5k9x9liVsedYqMZ7T/LqTTnwtk0QukroRHqtkbU1WPoZF59W9WZmCUvLiQaptvlBZ7cLOJCBOLUR0mZm/iJkDslScTzGxNm9XYiWCebtAi5R8TtZQfCZ2TcR5BOsV1kIvC/XZntA9Pm5etsGxe5yC032eq32HJH6xItJRnW/7O8MWlM=
