env:
  global:
    - IMAGE_NAME=pybot
    - DEPLOY_BRANCHES="master staging"
    - AWS_REGION=us-east-2
    - secure: DcEpdVJ6LoHSLigVem++aZGn0kq74oyPIk/Zifz61NE7nDbustbXahgtMCkiv7dqyd1nqc6E/9S/DZ5dUoWPeeG/VPKkm+Ylk0jZcVLPwSd9S3oICLIZVwL8bG+FwYEY08kGl20rbTMAZT3zIhT0HMmw59UVYr7Lke9vLy2sZKi3nZv7L6miiIBwK3DFuUx3cPTtNXiaszBbUmFLNTNg6ehig2W+FwhHEG2wmd+On5nmArdaXfBDKMXT748aA2y3OG3PTrXdC5OEi0oIaf/8MimIJWzxkoMS8jFoyDSXFOCOzQucv7uAsZHZRACP2HHV5iqOLIo5E6dlONKJFP7TCYqYTzZF8Dz9TUjIMkr+zAeCMrlMzOCVD3qquUoW++s6F71IHGlavqZvMTApyaRCIZanwHk/Tb96/s87bsFPYoGrsInQjfhhPUHTCxZrkBqZg8UegbZJ+HyH+I0bK9WM5mFyeQ7swRFkaQ6MICmqWF0w8JrJUAkOci3Q6NO1+7NBDNT5F3arhHgKMHpw0ry3iuUU1I7Unh8QdzNIgdcAh7TAgI8n0CjBXHf22+ZI0ph4Og7blZ17h9idSj72Ll8a7Rnj3/FgtB7HE1nQMzZfBtiN6txZAhM1ADIDj6NmaIXF+2hkQDnGczGaLqNHlKb14nNfdiWnO8Wf9DKCFZS8iKk=
    - secure: XPvMPMkCIBORXmFSwnSVm6rOF1mHcipzgo9IdbFu87dFFC2mJG/T8UTbEyTLpjpM8WvcSawmpWHtqlhbHXnEj+6ugEongvYsl0wYh/KNU9oS5vw38CvxpvIIg3PyTS39Dp8QtP/y/EaeZPPQiN/soiNGQ0EQ9V/eazjO9Gc9vTvYfPdSc3Q4UjxAqf550L+pkEF6NSh0Lo3ShCr1sai+XCvyvYeTTtwZzufIzq/aNxs+dPUc0FDXdZ5L+J2Ds/yxXAaVcQzSfhdxV1igCcQ6HesndsrrM6DIOTPtzFhpeA3RHaNxrAeh9ZXvYoLkXbyxEmraSRTx0PBjBLNkZNNorOB/ebWj3s1CK5I/3qrZ7WVIq/keDea1Ict9g7moYe8/OLQO0b0/gNqkR/jpepSbfxnEF41DNhJ2xSSE9niuEaUnpDpCibhLCqtXGbRK90dIjnkLHemxL8mrujwm7XDHcTK+GsA5ceBMHk0aQ9WDrKPCQGw8DlQ6EfgnOd/61Dq5vMZW8cC60h8EQNQFQ3KBgEEELpNSltvaf4FYA3Og+Vie/VStjCzDuGohghKiiaGFBWUGtaQGyr4cuwCI88iAU4/LiTz83JAv7+6tD+vsczV8Bdlg360Mquc01E7Vw9Qmtvh1kRWLicA6dUemrUqHO79izqAhhmLhz5dCBZOOGoM=
    - AIRTABLE_API_KEY=apiKey
    - AIRTABLE_BASE_KEY=baseKey
    - AIRTABLE_VERIFY=verify
    - ECS_CLUSTER_MASTER=python-oc-services
    - ECS_SERVICE_MASTER=pybot-svc
    - ECS_CLUSTER_STAGING=python-oc-services
    - ECS_SERVICE_STAGING=pybot-svc-staging
    - PIPENV_CACHE_DIR=~./.cache/pip
    - REMOTE_IMAGE_URL=docker.io/operationcode/pybot
    - DOCKER_REPO=operationcode/pybot
    - secure: HW7Pz/lP9e7V5vd+otoQJPWLt9aoubbHjREnkjUWHrcPu7muh18P4BkqeNxpotZ+B+OQPNKnjrFKOTmqhe+BprUktfsuiyr7wrG0PFVBGInkLBKJIKOGtxDQ06QzzTrAe03EKxZ69qdd9dFE0GS2a0DgYBljmBVvSaPrbox6vQPUjA/Tm8NoPeuHgku0C72wmFf/Lq7BV53YnLxFGI5o1HUOeEIX+C3YC2XKZME49bhfuTfELHuAFkriCsrsZVlivoSpDCcHluoSE3GJTkH4c91202nhzGv82iMfFvGpCvEMsafbvBZEbWn+OG+m6I3LbcFGbzd/T4tZgq8FPVrJBdOFK8nF2lSycTSLyQSEtfCXleK/2JD8Y5Q9PIRVBMv0pqusdM4Cb87gvMoe/6Lz4jidNNIAsqONXlfBjQ6fxs/hmuUVt3ldmh8M+KeE43gyu6avycqT5ggLvEI9cezqxTLA64EylAWGNGoVOIb20VufyXsfAFukuVT4ZJlO5ew3rxxlgH/3CT7Bs9e20cbzprejYPMqwQ3MuflRoSkq85gfuxpo017hESNJ0hiMUOWsKiizB6qx0N6yfrGwFhAs7bRDBwfjcyeGmhZAA96LBhwWLqTv+hhvT+Ipd+npUVYGGQHCEa45A3e0yS4V6N5CVxg8vuXeZNgDrd90MYhfaVs=
    - secure: ZUFgshGIrB41poEbRSxcAJ8mpmFWf0KtQt/yc61bz+R1W4EyDtsb7gborENt1XenXQkyqsh18s+TMCmr8BKNHMMWn9lBc5rx+5iWEK5VRNW3N55t5Eh8nDuBTrFHZqb5wSkK1fdJxmpxFBYlm9+iHbU0NEZ5iCR3qXvI1yCu1vLghm0oZOV+fUyncIKlbevDO0fX3hysd9M2v97eGes0ZtZVX+ZCIR7bK3hBcL4n2QdQgFiu3q85NOt3H1ruEerGllpYYqb95pbcMTqRaluUWffTAAnqtxgCaEkkNPkl5aQYlYYk865i/2ktXUTZjjoDD6HVLwsDVLteAqiNqDjxwvnjRWxYSQzMNvaxabCukEnW1XQvxSuI89/XiwBHTQaqkH3+M1QLfWdPAj3+0SZLwmOB5zrzAk3pQcekEB5zEa0bF0HpUhJffVbPLwDv/pvIpKUFrd+C8IdaqJmhNup6wL1BAgSb0PImxpbACDBL6xkm7w0Il6CJRL1KmhQYRcixXwZFnFsABb1QLqIBTyyb5+ETgBhBGndJKqIWjSVEKIN+PSgPpZKNybAUxxCKPUFzlyWseA1aRSMAr3BsQe2vfMwDzCXwRa3i+fpcudlaMysIkP4Y6y0B/qFHk26VEr653NQGfUFpul+XtR016TPsUOUr/mi6oc2TIzqsOtc5DPk=

os: linux
cache: pip
sudo: required
language: python
dist: xenial
python: 3.7
install:
  - pip install pipenv
  - pipenv install --system --deploy --dev
script:
  - pytest
services:
  - docker
after_success:
  - bash bin/run.sh
notifications:
  slack:
    rooms:
      secure: WXY1MpTRyv7B+t0HhLGjkIfiujU7q4+CB6oyxFFqO62cSv4LgV2efoYS9qZCcxbNQNRnzBjVLWD+d0afXhhsBOrjTMadjJdc+mzZyKiS8Hc21ZK8vH8o7ivmbxT63hMTbYdXY5mPdOpd13zszCibJowE5g9ce1MA/W5VLuQlAxdLb5/hnIaAY5Ik5A03tC3jFiELF5n0f/+U4TWR2XYWl13Zh72oqARKvTSLCQg83yCA1gG3eniOZTOsk0uK2ob3IBpmlb7MM/wg6JNN/zEFQ2J5dxNpsSTVvq44dKDAG7ebWXuc7Ba2bkzqQsTvuzRaYUeXJEpHs9AmygmPa5ndnVcXYYv9EiwTI+hb49sZNaE4gPpnJVlSrSMCffdAb/63VeKn1am3mREbtt5oo1OU/jt5wyRU17e16j3AxykoTaAb4jJXSICLsUgP7svTj1ByQuWnyGL7/y394tftckxMDCiLtaBcOTtxsGNA6BuKYXs76jbjy9A4KLMWn1FJ5k9x9liVsedYqMZ7T/LqTTnwtk0QukroRHqtkbU1WPoZF59W9WZmCUvLiQaptvlBZ7cLOJCBOLUR0mZm/iJkDslScTzGxNm9XYiWCebtAi5R8TtZQfCZ2TcR5BOsV1kIvC/XZntA9Pm5etsGxe5yC032eq32HJH6xItJRnW/7O8MWlM=
